### ISSUE TITLE
Hazelcast client on android device throws java.lang.NoClassDefFoundError: com.hazelcast.client.txn.proxy.xa.XAResourceProxy after upgrading from 3.4.2 to 3.5.2 

### ISSUE THREAD

**Issue by manikuramboyina** [hazelcast/hazelcast#6102]
We use hazelcast in production and part of our system involves some operations on android for which we use hazelcast queues. 
So far, there were no issues before the upgrade.
Once upgraded from 3.4.2 to 3.5.2, hazelcast client throws "java.lang.NoClassDefFoundError: com.hazelcast.client.txn.proxy.xa.XAResourceProxy" and the android app crashes even before it starts.
We've tried reproducing the issues with the other releases of hazelcast  (3.4.3, 3.4.4, 3.4.5). All the 3.4.x releases seem to work fine. 
We also tried to search through any existing cases who faced this issue and unfortunately, we couldn't find any such reported issues.

 To keep you guys informed, we tried the following to resolve this:
- Tried different releases in 3.5.x. All result in the same error.
- We tried using different android devices. This occurs only if we use hazelcast client on Android.
- Invalidated android studio cache and cleaned project, so that there could be no discrepancies in the dependency resolution.
- Tried directly including hazelcast jars manually in the libraries without using the build tools.

logcat Log:

08-31 23:14:30.918  13746-13746/sg.company.testserver D/dalvikvm﹕ GetMethodID: not returning static method Landroid/os/Process;.getTotalMemory ()J
08-31 23:14:30.918  13746-13746/sg.company.testserver D/dalvikvm﹕ GetMethodID: not returning static method Landroid/os/Process;.getFreeMemory ()J
08-31 23:14:30.998  13746-13746/sg.company.testserver I/dalvikvm﹕ Failed resolving Lcom/hazelcast/transaction/HazelcastXAResource; interface 5813 'Ljavax/transaction/xa/XAResource;'
08-31 23:14:30.998  13746-13746/sg.company.testserver W/dalvikvm﹕ Link of class 'Lcom/hazelcast/transaction/HazelcastXAResource;' failed
08-31 23:14:30.998  13746-13746/sg.company.testserver E/dalvikvm﹕ Could not find class 'com.hazelcast.transaction.HazelcastXAResource', referenced from method com.hazelcast.client.impl.HazelcastClientInstanceImpl.getXAResource
08-31 23:14:30.998  13746-13746/sg.company.testserver W/dalvikvm﹕ VFY: unable to resolve check-cast 5154 (Lcom/hazelcast/transaction/HazelcastXAResource;) in Lcom/hazelcast/client/impl/HazelcastClientInstanceImpl;
08-31 23:14:30.998  13746-13746/sg.company.testserver D/dalvikvm﹕ VFY: replacing opcode 0x1f at 0x0008
08-31 23:14:31.078  13746-13746/sg.company.testserver I/LifecycleService﹕ HazelcastClient[hz.client_0_dev][3.5.2] is STARTING
08-31 23:14:31.098  13746-13746/sg.company.testserver I/dalvikvm﹕ Failed resolving Lcom/hazelcast/cache/HazelcastExpiryPolicy; interface 5734 'Ljavax/cache/expiry/ExpiryPolicy;'
08-31 23:14:31.098  13746-13746/sg.company.testserver W/dalvikvm﹕ Link of class 'Lcom/hazelcast/cache/HazelcastExpiryPolicy;' failed
08-31 23:14:31.098  13746-13746/sg.company.testserver E/dalvikvm﹕ Could not find class 'com.hazelcast.cache.HazelcastExpiryPolicy', referenced from method com.hazelcast.cache.impl.CacheDataSerializerHook$19.createNew
08-31 23:14:31.098  13746-13746/sg.company.testserver W/dalvikvm﹕ VFY: unable to resolve new-instance 38 (Lcom/hazelcast/cache/HazelcastExpiryPolicy;) in Lcom/hazelcast/cache/impl/CacheDataSerializerHook$19;
08-31 23:14:31.098  13746-13746/sg.company.testserver D/dalvikvm﹕ VFY: replacing opcode 0x22 at 0x0000
08-31 23:14:31.098  13746-13746/sg.company.testserver I/dalvikvm﹕ Failed resolving Lcom/hazelcast/cache/HazelcastExpiryPolicy; interface 5734 'Ljavax/cache/expiry/ExpiryPolicy;'
08-31 23:14:31.098  13746-13746/sg.company.testserver W/dalvikvm﹕ Link of class 'Lcom/hazelcast/cache/HazelcastExpiryPolicy;' failed
08-31 23:14:31.098  13746-13746/sg.company.testserver D/dalvikvm﹕ DexOpt: unable to opt direct call 0x0067 at 0x02 in Lcom/hazelcast/cache/impl/CacheDataSerializerHook$19;.createNew
08-31 23:14:31.128  13746-13746/sg.company.testserver I/dalvikvm﹕ Could not find method sun.misc.Unsafe.putChar, referenced from method com.hazelcast.nio.UnsafeHelper.<clinit>
08-31 23:14:31.128  13746-13746/sg.company.testserver W/dalvikvm﹕ VFY: unable to resolve virtual method 45380: Lsun/misc/Unsafe;.putChar (Ljava/lang/Object;JC)V
08-31 23:14:31.128  13746-13746/sg.company.testserver D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0081
08-31 23:14:31.128  13746-13746/sg.company.testserver W/UnsafeHelper﹕ sun.misc.Unsafe has been disabled because your platform does not support unaligned access to memory, some features might be not available.
08-31 23:14:31.138  13746-13746/sg.company.testserver I/dalvikvm﹕ Failed resolving Lcom/hazelcast/transaction/HazelcastXAResource; interface 5813 'Ljavax/transaction/xa/XAResource;'
08-31 23:14:31.138  13746-13746/sg.company.testserver W/dalvikvm﹕ Link of class 'Lcom/hazelcast/transaction/HazelcastXAResource;' failed
08-31 23:14:31.138  13746-13746/sg.company.testserver I/dalvikvm﹕ Failed resolving Lcom/hazelcast/client/txn/proxy/xa/XAResourceProxy; interface 5154 'Lcom/hazelcast/transaction/HazelcastXAResource;'
08-31 23:14:31.138  13746-13746/sg.company.testserver W/dalvikvm﹕ Link of class 'Lcom/hazelcast/client/txn/proxy/xa/XAResourceProxy;' failed
08-31 23:14:31.138  13746-13746/sg.company.testserver E/dalvikvm﹕ Could not find class 'com.hazelcast.client.txn.proxy.xa.XAResourceProxy', referenced from method com.hazelcast.client.spi.ProxyManager.init
08-31 23:14:31.138  13746-13746/sg.company.testserver W/dalvikvm﹕ VFY: unable to resolve const-class 2185 (Lcom/hazelcast/client/txn/proxy/xa/XAResourceProxy;) in Lcom/hazelcast/client/spi/ProxyManager;
08-31 23:14:31.138  13746-13746/sg.company.testserver D/dalvikvm﹕ VFY: replacing opcode 0x1c at 0x006f
08-31 23:14:31.148  13746-13746/sg.company.testserver D/AndroidRuntime﹕ Shutting down VM
08-31 23:14:31.148  13746-13746/sg.company.testserver W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41dd9d58)
08-31 23:14:31.148  13746-13746/sg.company.testserver E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: sg.company.testserver, PID: 13746
    java.lang.NoClassDefFoundError: com.hazelcast.client.txn.proxy.xa.XAResourceProxy
            at com.hazelcast.client.spi.ProxyManager.init(ProxyManager.java:124)
            at com.hazelcast.client.impl.HazelcastClientInstanceImpl.<init>(HazelcastClientInstanceImpl.java:165)
            at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:84)
            at sg.company.testserver.QueueService$SMSSender.<init>(QueueService.java:68)
            at sg.company.testserver.QueueService.start(QueueService.java:144)
            at sg.company.testserver.DashboardActivity.onCreate(DashboardActivity.java:93)
            at android.app.Activity.performCreate(Activity.java:5248)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
            at android.app.ActivityThread.access$800(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5052)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
            at dalvik.system.NativeStart.main(Native Method)

 Our Hazelcast configuration:
                // Hazel cast config
                ClientNetworkConfig networkConfig = new ClientNetworkConfig();
                networkConfig.addAddress("xxxxxx");
                networkConfig.addAddress("xxxxxx");
                networkConfig.addAddress("xxxxxxx");
                networkConfig.setConnectionAttemptLimit(0);
                networkConfig.setConnectionAttemptPeriod(3000);
                ClientConfig clientConfig = new ClientConfig().setNetworkConfig(networkConfig);
                GroupConfig groupConfig = new GroupConfig();
                groupConfig.setName("xxxxxxxxx");
                groupConfig.setPassword("xxxxxxxx");
                clientConfig.setGroupConfig(groupConfig);

                hazelcastClient = HazelcastClient.newHazelcastClient(clientConfig);

**Comment by pveentjer** [comment]
This class was added in Hazelcast 3.5.

The big question is: why is this class not found while many other classes
are found.

**Comment by gurbuzali** [comment]
Although there is no exception at the logcat, there are other classes which couldn't be found :
```
Failed resolving Lcom/hazelcast/transaction/HazelcastXAResource; interface 5813 'Ljavax/transaction/xa/XAResource;'
Failed resolving Lcom/hazelcast/cache/HazelcastExpiryPolicy; interface 5734 'Ljavax/cache/expiry/ExpiryPolicy;'
Failed resolving Lcom/hazelcast/client/txn/proxy/xa/XAResourceProxy; interface 5154 'Lcom/hazelcast/transaction/HazelcastXAResource;'
```

**Comment by pveentjer** [comment]
Which Hazelcast jars are you using? Are they modified by any chance (e.g.
stuff removed to reduce size).

**Comment by jerrinot** [comment]
@manikuramboyina: First of all thank you very much for reporting the issue.

The issue is perfectly explainable. We have somewhat changed internal implementation of transactions in Hazelcast 3.5. It now relies on `javax.transaction.xa.XAResource` class. The class is part of standard Java library, but unfortunately unavailable on Android.

**Comment by manikuramboyina** [comment]
@jerrinot 
That's sad, so only resolution for now, is rolling back to 3.4.x ?

**Comment by jerrinot** [comment]
@manikuramboyina: I'm afraid that's the case for now. 

You *could* try some hacks such as to create an empty `XAResource` class and package it as a part of your application or something like that. However that's obviously something I can't recommend doing.

**Comment by jerrinot** [comment]
I'm labelling this is a Defect as it's a regression

**Comment by enesakar** [comment]
moving to backlog, currently android is not supported.

**Comment by hongphu8790** [comment]
What's status now?
