### ISSUE TITLE
JDK11 compile failure

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15583]
Failing on JDK11, might be related with https://github.com/hazelcast/hazelcast/pull/15572

_master_ (commit 36550fd1ad660d5962c12e52e7aeeadb420f5502)

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK11/81/console

```
10:42:06 [ERROR] COMPILATION ERROR : 
10:42:06 [INFO] -------------------------------------------------------------
10:42:06 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/internal/memory/impl/UnsafeUtil.java:[22,15] Unsafe is internal proprietary API and may be removed in a future release
10:42:06 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/CPAtomicLongCompareAndSetCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/CPAtomicLongCompareAndSetCodec.java:[39,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/internal/memory/impl/UnsafeUtil.java:[22,15] Unsafe is internal proprietary API and may be removed in a future release
10:42:06 [ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MapSetCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MapSetCodec.java:[40,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ClientAddMembershipListenerCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ClientAddMembershipListenerCodec.java:[39,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MultiMapEntrySetCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MultiMapEntrySetCodec.java:[39,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ReplicatedMapGetCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ReplicatedMapGetCodec.java:[41,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MapGetCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MapGetCodec.java:[39,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/CacheAssignAndGetUuidsCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/CacheAssignAndGetUuidsCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ScheduledExecutorShutdownCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ScheduledExecutorShutdownCodec.java:[39,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MultiMapIsLockedCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MultiMapIsLockedCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MapAddNearCacheInvalidationListenerCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MapAddNearCacheInvalidationListenerCodec.java:[41,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MultiMapRemoveCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MultiMapRemoveCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ScheduledExecutorIsCancelledFromAddressCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ScheduledExecutorIsCancelledFromAddressCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/CPSemaphoreReleaseCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/CPSemaphoreReleaseCodec.java:[39,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/CacheFetchNearCacheInvalidationMetadataCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/CacheFetchNearCacheInvalidationMetadataCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MultiMapContainsEntryCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MultiMapContainsEntryCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/AtomicReferenceCompareAndSetCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/AtomicReferenceCompareAndSetCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/QueueRemoveListenerCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/QueueRemoveListenerCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ListContainsCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ListContainsCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MapAddEntryListenerToKeyCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MapAddEntryListenerToKeyCodec.java:[40,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/AtomicLongGetCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/AtomicLongGetCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/QueuePutCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/QueuePutCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ConditionAwaitCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ConditionAwaitCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MultiMapDeleteCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MultiMapDeleteCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/SetAddCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/SetAddCodec.java:[43,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ListAddListenerCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ListAddListenerCodec.java:[39,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/RingbufferTailSequenceCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/RingbufferTailSequenceCodec.java:[39,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/CacheSizeCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/CacheSizeCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/SetContainsCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/SetContainsCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MultiMapAddEntryListenerCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/MultiMapAddEntryListenerCodec.java:[39,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ContinuousQueryDestroyCacheCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/ContinuousQueryDestroyCacheCodec.java:[38,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/DynamicConfigAddReliableTopicConfigCodec.java:[22,23] error: cannot find symbol
10:42:06 [ERROR]   symbol:   class Generated
10:42:06   location: package javax.annotation
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/DynamicConfigAddReliableTopicConfigCodec.java:[40,1] error: cannot find symbol
10:42:06 [ERROR]   symbol: class Generated
10:42:06 /home/jenkins/jenkins_slave/workspace/Hazelcast-3.x-OracleJDK11/hazelcast/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/codec/QueueAddListenerCodec.java:[22,23] error: cannot find symbol
```
